version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schooldb
    ports:
      - "5433:5432"
    networks:
      - pg-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - postgres  # Ensures pgAdmin waits for postgres to start

networks:
  pg-network:
    driver: bridge

volumes:
  postgres_data:
